/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.jzinv.receive;
	
import nc.itf.jzinv.pub.IBillCode;
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 收票表头 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2016-03-16 10:46:06
 * @author Administrator
 * @version NCPrj 1.0
 */
public class ReceiveVO extends SuperVO  implements IBillCode{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String vdef8;
	private String vdef7;
	private String vdef9;
	private UFDate dtodate;
	private UFDouble ntaxmny;
	private String pk_projectbase;
	private String vdef2;
	private String vdef1;
	private String vdef4;
	private String vdef3;
	private String vdef6;
	private String vdef5;
	private UFDouble norighadsetlevefymny;
	private UFDouble norighadsetlevefytaxmny;
	private UFDouble ninvmny;
	private String pk_authenpsn;
	private String vtaxpayeraddress;
	private UFDate dauthendate;
	private UFDouble norignopayvefymny;
	private UFDouble noriginvmny;
	private String vtaxpayernumber;
	private String pk_basetype;
	private UFDouble noriginvtaxmny;
	private UFDate dopendate;
	private String vbankaccount;
	private String vreserve1;
	private String pk_psndoc;
	private String vtaxpayername;
	private String vreserve4;
	private String vreserve5;
	private String vreserve2;
	private String vreserve3;
	private String voperatorid;
	private String vapprovenote;
	private String vsupplierphone;
	private UFDouble norighadpayvefytaxmny;
	private String vapproveid;
	private String vreserve9;
	private UFBoolean bisred;
	private String vreserve8;
	private String vreserve7;
	private String vreserve6;
	private Integer dr;
	private String vtaxctrlmachno;
	private String vraddress;
	private String pk_supplier;
	private String pk_finance;
	private String pk_project;
	private String vbillno;
	private String pk_deptdoc;
	private String pk_supplierbase;
	private UFDateTime ts;
	private String vinvcode;
	private UFDate dmakedate;
	private String vtaxpayerphone;
	private String vsupbankaccount;
	private UFDouble norignosetlevefytaxmny;
	private String vtaxsuppliernumber;
	private String pk_receive_ref;
	private UFDouble nbaserate;
	private UFDouble nhadsetlevefymny;
	private String vreserve10;
	private String pk_billtype;
	private UFDouble ntaxrate;
	private String vdef10;
	private String vdef11;
	private UFBoolean bisauthen;
	private String vdef15;
	private String vinvno;
	private String vdef14;
	private String vdef13;
	private String vdef12;
	private String vdef19;
	private String vdef18;
	private String pk_industryclassify;
	private String vdef17;
	private String vdef16;
	private UFDate dbilldate;
	private UFDouble ninvtaxmny;
	private String pk_bank;
	private UFDouble norighadpayvefymny;
	private String pk_origintype;
	private UFDouble norignopayvefytaxmny;
	private String vdef20;
	private UFDouble nnopayvefymny;
	private String vsupplieraddress;
	private String vmemo;
	private UFDouble nhadpayvefymny;
	private UFDouble nhadpayvefytaxmny;
	private UFDouble nhadsetlevefytaxmny;
	private String pk_corp;
	private UFBoolean bisopenred;
	private String vphone;
	private UFDouble nnopayvefytaxmny;
	private String pk_receive;
	private UFDouble norignosetlevefymny;
	private UFDouble nnosetlevefymny;
	private Integer vbillstatus;
	private UFDate dapprovedate;
	private UFDouble nnosetlevefytaxmny;
	/**
	 * 费用类型
	 */
	private String pk_feebasinfo;
	/**
	 * 认证方式
	 */
	private Integer iauthentype;
	/**
	 * 费用类型
	 */
	public static String PK_FEEBASINFO = "pk_feebasinfo";
	/**
	 * 认证方式
	 */
	public static String IAUTHENTYPE = "iauthentype";
	
	/**
	 * 费用已抵扣金额(无税)
	 */
	private UFDouble noriginfhaddductmny;
	/**
	 * 费用已抵扣金额
	 */
	private UFDouble noriginfhaddducttaxmny;
	/**
	 * 费用已抵扣金额(无税)(本币)
	 */
	private UFDouble nfhaddductmny;
	/**
	 * 费用已抵扣金额(本币)
	 */
	private UFDouble nfhaddducttaxmny;
	/**
	 * 费用已抵扣金额
	 */
	public static String NORIGINFHADDDUCTTAXMNY = "noriginfhaddducttaxmny";
	public static String NORIGINFHADDDUCTMNY = "noriginfhaddductmny";
	public static String NFHADDDUCTMNY = "nfhaddductmny";
	public static String NFHADDDUCTTAXMNY = "nfhaddducttaxmny";
	/**
	 * 付款公司
	 */
	private String pk_paycorp;
    /**
     * 合同
     */
	private String pk_contract;
	/**
	 * 回冲金额
	 */
	private UFDouble norigbackmny;
	private UFDouble nbackmny;
	private UFDouble norigbacktaxmny;
	private UFDouble nbacktaxmny;
	/**
	 * 红票TS
	 */
	private UFDateTime redts;
	 /**
     * 已开红票金额
     */
	private UFDouble norighadredmny;
	private UFDouble norighadredtaxmny;
	private UFDouble nhadredmny;
	private UFDouble nhadredtaxmny;
	/**
	 * 认证截至日期
	 */
	private UFDate denddate;
	/**
	 * 是否传金税
	 */
	private UFBoolean bistransfertax;
	public static final String BISTRANSFERTAX = "bistransfertax";
    public static final String DENDDATE = "denddate";
	/**
	 * 已开红票金额
	 */
	public static final String NORIGHADREDMNY = "norighadredmny";
	public static final String NORIGHADREDTAXMNY = "norighadredtaxmny";
	public static final String NHADREDMNY = "nhadredmny";
	public static final String NHADREDTAXMNY = "nhadredtaxmny";
	/**
	 * 上层单据ID
	 */
	private String vlastbillid;
	/**
	 * 上层单据行ID
	 */
	private String vlastbillrowid;
	/**
	 * 上层单据类型
	 */
	private String vlastbilltype;
	/**
	 * 红票TS
	 */
	public static final String REDTS = "redts";
	
	public static final String VLASTBILLID = "vlastbillid";
	public static final String VLASTBILLROWID = "vlastbillrowid";
	public static final String VLASTBILLTYPE = "vlastbilltype";
	/**
	 * 传会计平台
	 */
	private UFBoolean bisupload;
	public static final String BISUPLOAD = "bisupload";
	/**
	 * 认证状态
	 */
	private Integer iauthstatus;
	/**
	 * 密文
	 */
	private String vsecret;
	private String vuploadfilename;
	/**
	 * 认证状态
	 */
	public static final String IAUTHSTATUS = "iauthstatus";
	/**
	 * 密文
	 */
	public static final String VSECRET = "vsecret";
	public static final String VUPLOADFILENAME = "vuploadfilename";
	/**
	 * 认证次数
	 */
	private Integer iauthcount;
	/**
	 * 认证次数
	 */
	public static final String IAUTHCOUNT = "iauthcount";
	/**
	 * 红字开票申请原因
	 */
	private Integer iredaplyreason;
	/**
	 * 红字开票申请原因
	 */
	public static final String IREDAPLYREASON = "iredaplyreason";
	/**
	 * 红字专用发票信息表编号
	 */
	private String vredinfono;
	/**
	 * 红字专用发票信息表编号
	 */
	public static final String VREDINFONO = "vredinfono";
	/**
	 * 认证期
	 */
	private String vauthperiod;
	public static final String VAUTHPERIOD = "vauthperiod";
	/**
	 * 纳税期
	 */
	private String vtaxperiod;
	/**
	 * 纳税期
	 */
	public static final String VTAXPERIOD = "vtaxperiod";
	/**
	 * 发票类型
	 */
	private Integer iinvtype;
	/**
	 * 发票类型
	 */
	public static final String IINVTYPE = "iinvtype";
	/**
	 * 供应商类型
	 */
	private Integer isupplytype;
	/**
	 * 供应商类型
	 */
	public static final String ISUPPLYTYPE = "isupplytype";

	public Integer getIsupplytype() {
		return isupplytype;
	}
	public void setIsupplytype(Integer isupplytype) {
		this.isupplytype = isupplytype;
	}
	public String getPk_feebasinfo() {
		return pk_feebasinfo;
	}
	public void setPk_feebasinfo(String pk_feebasinfo) {
		this.pk_feebasinfo = pk_feebasinfo;
	}
	public Integer getIauthentype() {
		return iauthentype;
	}
	public void setIauthentype(Integer iauthentype) {
		this.iauthentype = iauthentype;
	}
	public Integer getIinvtype() {
		return iinvtype;
	}
	public void setIinvtype(Integer iinvtype) {
		this.iinvtype = iinvtype;
	}
	public String getVtaxperiod() {
		return vtaxperiod;
	}
	public void setVtaxperiod(String vtaxperiod) {
		this.vtaxperiod = vtaxperiod;
	}
	/**
	 * 
	 * 出口退税
	 * sujbc2016-6-16上午2:00:26
	 */
	private UFBoolean bisdrawback;
	
	public static final String BISDRAWBACK = "bisdrawback";
	
	//linan 20171023 增加字段 begin
	//增加字段是否拆分字段 
	private UFBoolean bissplit;
	
	public static final String BISSPLIT = "bissplit";
	
	public UFBoolean getBissplit() {
		return bissplit;
	}
	public void setBissplit(UFBoolean bissplit) {
		this.bissplit = bissplit;
	}
	//增加票面总金额 无税
	private UFDouble ntotalinvoiceamountmny;
	
	public static final String NTOTALINVOICEAMOUNTMNY = "ntotalinvoiceamountmny";

	public UFDouble getNtotalinvoiceamountmny() {
		return ntotalinvoiceamountmny;
	}
	public void setNtotalinvoiceamountmny(UFDouble ntotalinvoiceamountmny) {
		this.ntotalinvoiceamountmny = ntotalinvoiceamountmny;
	}
	//增加票面总金额 含税
	private UFDouble ntotalinvoiceamounttaxmny;
	
	public UFDouble getNtotalinvoiceamounttaxmny() {
		return ntotalinvoiceamounttaxmny;
	}
	public void setNtotalinvoiceamounttaxmny(UFDouble ntotalinvoiceamounttaxmny) {
		this.ntotalinvoiceamounttaxmny = ntotalinvoiceamounttaxmny;
	}
	public static final String NTOTALINVOICEAMOUNTTAXMNY = "ntotalinvoiceamounttaxmny";
	
	//增加发票总税金
	private UFDouble ntotalinvoicetax; 
	
	public UFDouble getNtotalinvoicetax() {
		return ntotalinvoicetax;
	}
	public void setNtotalinvoicetax(UFDouble ntotalinvoicetax) {
		this.ntotalinvoicetax = ntotalinvoicetax;
	}
	public static final String NTOTALINVOICETAX = "ntotalinvoicetax";
	
	//累计已拆分税金
	private UFDouble ncumulativesplittax; 
	public UFDouble getNcumulativesplittax() {
		return ncumulativesplittax;
	}
	public void setNcumulativesplittax(UFDouble ncumulativesplittax) {
		this.ncumulativesplittax = ncumulativesplittax;
	}
	public static final String NCUMULATIVESPLITTAX = "ncumulativesplittax";
	
	//剩余拆分税金金额
	private UFDouble nsurplussplittax;
	
	public static final String NSURPLUSSPLITTAX = "nsurplussplittax";
	
	public UFDouble getNsurplussplittax() {
		return nsurplussplittax;
	}
	public void setNsurplussplittax(UFDouble nsurplussplittax) {
		this.nsurplussplittax = nsurplussplittax;
	}
	//linan 20171023 增加字段 end
	public String getVauthperiod() {
		return vauthperiod;
	}
	public void setVauthperiod(String vauthperiod) {
		this.vauthperiod = vauthperiod;
	}
	public Integer getIredaplyreason() {
		return iredaplyreason;
	}
	public void setIredaplyreason(Integer iredaplyreason) {
		this.iredaplyreason = iredaplyreason;
	}
	public String getVredinfono() {
		return vredinfono;
	}
	public void setVredinfono(String vredinfono) {
		this.vredinfono = vredinfono;
	}
	public Integer getIauthcount() {
		return iauthcount;
	}
	public void setIauthcount(Integer iauthcount) {
		this.iauthcount = iauthcount;
	}
	public Integer getIauthstatus() {
		return iauthstatus;
	}
	public void setIauthstatus(Integer iauthstatus) {
		this.iauthstatus = iauthstatus;
	}
	
	public String getVsecret() {
		return vsecret;
	}
	public void setVsecret(String vsecret) {
		this.vsecret = vsecret;
	}
	public String getVuploadfilename() {
		return vuploadfilename;
	}
	public void setVuploadfilename(String vuploadfilename) {
		this.vuploadfilename = vuploadfilename;
	}
	public UFBoolean getBisupload() {
		return bisupload;
	}
	public void setBisupload(UFBoolean bisupload) {
		this.bisupload = bisupload;
	}
	public UFBoolean getBistransfertax() {
		return bistransfertax;
	}
	public void setBistransfertax(UFBoolean bistransfertax) {
		this.bistransfertax = bistransfertax;
	}
	public String getVlastbillid() {
		return vlastbillid;
	}
	public void setVlastbillid(String vlastbillid) {
		this.vlastbillid = vlastbillid;
	}
	public String getVlastbillrowid() {
		return vlastbillrowid;
	}
	public void setVlastbillrowid(String vlastbillrowid) {
		this.vlastbillrowid = vlastbillrowid;
	}
	public String getVlastbilltype() {
		return vlastbilltype;
	}
	public void setVlastbilltype(String vlastbilltype) {
		this.vlastbilltype = vlastbilltype;
	}
	public UFDate getDenddate() {
		return denddate;
	}
	public void setDenddate(UFDate denddate) {
		this.denddate = denddate;
	}
	public UFDateTime getRedts() {
		return redts;
	}
	public void setRedts(UFDateTime redts) {
		this.redts = redts;
	}
	public UFDouble getNorighadredmny() {
		return norighadredmny;
	}
	public void setNorighadredmny(UFDouble norighadredmny) {
		this.norighadredmny = norighadredmny;
	}
	public UFDouble getNorighadredtaxmny() {
		return norighadredtaxmny;
	}
	public void setNorighadredtaxmny(UFDouble norighadredtaxmny) {
		this.norighadredtaxmny = norighadredtaxmny;
	}
	public UFDouble getNhadredmny() {
		return nhadredmny;
	}
	public void setNhadredmny(UFDouble nhadredmny) {
		this.nhadredmny = nhadredmny;
	}
	public UFDouble getNhadredtaxmny() {
		return nhadredtaxmny;
	}
	public void setNhadredtaxmny(UFDouble nhadredtaxmny) {
		this.nhadredtaxmny = nhadredtaxmny;
	}
	public static final String VDEF8 = "vdef8";
	public static final String VDEF7 = "vdef7";
	public static final String VDEF9 = "vdef9";
	public static final String DTODATE = "dtodate";
	public static final String NTAXMNY = "ntaxmny";
	public static final String PK_PROJECTBASE = "pk_projectbase";
	public static final String VDEF2 = "vdef2";
	public static final String VDEF1 = "vdef1";
	public static final String VDEF4 = "vdef4";
	public static final String VDEF3 = "vdef3";
	public static final String VDEF6 = "vdef6";
	public static final String VDEF5 = "vdef5";
	public static final String NORIGHADSETLEVEFYMNY = "norighadsetlevefymny";
	public static final String NORIGHADSETLEVEFYTAXMNY = "norighadsetlevefytaxmny";
	public static final String NINVMNY = "ninvmny";
	public static final String PK_AUTHENPSN = "pk_authenpsn";
	public static final String VTAXPAYERADDRESS = "vtaxpayeraddress";
	public static final String DAUTHENDATE = "dauthendate";
	public static final String NORIGNOPAYVEFYMNY = "norignopayvefymny";
	public static final String NORIGINVMNY = "noriginvmny";
	public static final String VTAXPAYERNUMBER = "vtaxpayernumber";
	public static final String PK_BASETYPE = "pk_basetype";
	public static final String NORIGINVTAXMNY = "noriginvtaxmny";
	public static final String DOPENDATE = "dopendate";
	public static final String VBANKACCOUNT = "vbankaccount";
	public static final String VRESERVE1 = "vreserve1";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String VTAXPAYERNAME = "vtaxpayername";
	public static final String VRESERVE4 = "vreserve4";
	public static final String VRESERVE5 = "vreserve5";
	public static final String VRESERVE2 = "vreserve2";
	public static final String VRESERVE3 = "vreserve3";
	public static final String VOPERATORID = "voperatorid";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String VSUPPLIERPHONE = "vsupplierphone";
	public static final String NORIGHADPAYVEFYTAXMNY = "norighadpayvefytaxmny";
	public static final String VAPPROVEID = "vapproveid";
	public static final String VRESERVE9 = "vreserve9";
	public static final String BISRED = "bisred";
	public static final String VRESERVE8 = "vreserve8";
	public static final String VRESERVE7 = "vreserve7";
	public static final String VRESERVE6 = "vreserve6";
	public static final String VTAXCTRLMACHNO = "vtaxctrlmachno";
	public static final String VRADDRESS = "vraddress";
	public static final String PK_SUPPLIER = "pk_supplier";
	public static final String PK_FINANCE = "pk_finance";
	public static final String PK_PROJECT = "pk_project";
	public static final String VBILLNO = "vbillno";
	public static final String PK_DEPTDOC = "pk_deptdoc";
	public static final String PK_SUPPLIERBASE = "pk_supplierbase";
	public static final String VINVCODE = "vinvcode";
	public static final String DMAKEDATE = "dmakedate";
	public static final String VTAXPAYERPHONE = "vtaxpayerphone";
	public static final String VSUPBANKACCOUNT = "vsupbankaccount";
	public static final String NORIGNOSETLEVEFYTAXMNY = "norignosetlevefytaxmny";
	public static final String VTAXSUPPLIERNUMBER = "vtaxsuppliernumber";
	public static final String PK_RECEIVE_REF = "pk_receive_ref";
	public static final String NBASERATE = "nbaserate";
	public static final String NHADSETLEVEFYMNY = "nhadsetlevefymny";
	public static final String VRESERVE10 = "vreserve10";
	public static final String PK_BILLTYPE = "pk_billtype";
	public static final String NTAXRATE = "ntaxrate";
	public static final String VDEF10 = "vdef10";
	public static final String VDEF11 = "vdef11";
	public static final String BISAUTHEN = "bisauthen";
	public static final String VDEF15 = "vdef15";
	public static final String VINVNO = "vinvno";
	public static final String VDEF14 = "vdef14";
	public static final String VDEF13 = "vdef13";
	public static final String VDEF12 = "vdef12";
	public static final String VDEF19 = "vdef19";
	public static final String VDEF18 = "vdef18";
	public static final String PK_INDUSTRYCLASSIFY = "pk_industryclassify";
	public static final String VDEF17 = "vdef17";
	public static final String VDEF16 = "vdef16";
	public static final String DBILLDATE = "dbilldate";
	public static final String NINVTAXMNY = "ninvtaxmny";
	public static final String PK_BANK = "pk_bank";
	public static final String NORIGHADPAYVEFYMNY = "norighadpayvefymny";
	public static final String PK_ORIGINTYPE = "pk_origintype";
	public static final String NORIGNOPAYVEFYTAXMNY = "norignopayvefytaxmny";
	public static final String VDEF20 = "vdef20";
	public static final String NNOPAYVEFYMNY = "nnopayvefymny";
	public static final String VSUPPLIERADDRESS = "vsupplieraddress";
	public static final String VMEMO = "vmemo";
	public static final String NHADPAYVEFYMNY = "nhadpayvefymny";
	public static final String NHADPAYVEFYTAXMNY = "nhadpayvefytaxmny";
	public static final String NHADSETLEVEFYTAXMNY = "nhadsetlevefytaxmny";
	public static final String PK_CORP = "pk_corp";
	public static final String BISOPENRED = "bisopenred";
	public static final String VPHONE = "vphone";
	public static final String NNOPAYVEFYTAXMNY = "nnopayvefytaxmny";
	public static final String PK_RECEIVE = "pk_receive";
	public static final String NORIGNOSETLEVEFYMNY = "norignosetlevefymny";
	public static final String NNOSETLEVEFYMNY = "nnosetlevefymny";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String NNOSETLEVEFYTAXMNY = "nnosetlevefytaxmny";
			
	/**
	 * 付款公司
	 */
	public static final String PK_PAYCORP = "pk_paycorp";
	/**
	 * 合同
	 */
	public static final String PK_CONTRACT = "pk_contract";
	/**
	 * 回冲金额
	 */
	public static final String NORIGBACKMNY = "norigbackmny";
	public static final String NBACKMNY = "nbackmny";
	public static final String NORIGBACKTAXMNY = "norigbacktaxmny";
	public static final String NBACKTAXMNY = "nbacktaxmny";
	
	public UFDouble getNorigbackmny() {
		return norigbackmny;
	}
	public void setNorigbackmny(UFDouble norigbackmny) {
		this.norigbackmny = norigbackmny;
	}
	public UFDouble getNbackmny() {
		return nbackmny;
	}
	public void setNbackmny(UFDouble nbackmny) {
		this.nbackmny = nbackmny;
	}
	public UFDouble getNorigbacktaxmny() {
		return norigbacktaxmny;
	}
	public void setNorigbacktaxmny(UFDouble norigbacktaxmny) {
		this.norigbacktaxmny = norigbacktaxmny;
	}
	public UFDouble getNbacktaxmny() {
		return nbacktaxmny;
	}
	public void setNbacktaxmny(UFDouble nbacktaxmny) {
		this.nbacktaxmny = nbacktaxmny;
	}
	/**
	 * 属性vdef8的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef8 () {
		return vdef8;
	}   
	/**
	 * 属性vdef8的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef8 String
	 */
	public void setVdef8 (String newVdef8 ) {
	 	this.vdef8 = newVdef8;
	} 	  
	/**
	 * 属性vdef7的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef7 () {
		return vdef7;
	}   
	/**
	 * 属性vdef7的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef7 String
	 */
	public void setVdef7 (String newVdef7 ) {
	 	this.vdef7 = newVdef7;
	} 	  
	/**
	 * 属性vdef9的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef9 () {
		return vdef9;
	}   
	/**
	 * 属性vdef9的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef9 String
	 */
	public void setVdef9 (String newVdef9 ) {
	 	this.vdef9 = newVdef9;
	} 	  
	/**
	 * 属性dtodate的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDate
	 */
	public UFDate getDtodate () {
		return dtodate;
	}   
	/**
	 * 属性dtodate的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newDtodate UFDate
	 */
	public void setDtodate (UFDate newDtodate ) {
	 	this.dtodate = newDtodate;
	} 	  
	/**
	 * 属性ntaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNtaxmny () {
		return ntaxmny;
	}   
	/**
	 * 属性ntaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNtaxmny UFDouble
	 */
	public void setNtaxmny (UFDouble newNtaxmny ) {
	 	this.ntaxmny = newNtaxmny;
	} 	  
	/**
	 * 属性pk_projectbase的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_projectbase () {
		return pk_projectbase;
	}   
	/**
	 * 属性pk_projectbase的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_projectbase String
	 */
	public void setPk_projectbase (String newPk_projectbase ) {
	 	this.pk_projectbase = newPk_projectbase;
	} 	  
	/**
	 * 属性vdef2的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef2 () {
		return vdef2;
	}   
	/**
	 * 属性vdef2的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef2 String
	 */
	public void setVdef2 (String newVdef2 ) {
	 	this.vdef2 = newVdef2;
	} 	  
	/**
	 * 属性vdef1的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef1 () {
		return vdef1;
	}   
	/**
	 * 属性vdef1的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef1 String
	 */
	public void setVdef1 (String newVdef1 ) {
	 	this.vdef1 = newVdef1;
	} 	  
	/**
	 * 属性vdef4的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef4 () {
		return vdef4;
	}   
	/**
	 * 属性vdef4的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef4 String
	 */
	public void setVdef4 (String newVdef4 ) {
	 	this.vdef4 = newVdef4;
	} 	  
	/**
	 * 属性vdef3的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef3 () {
		return vdef3;
	}   
	/**
	 * 属性vdef3的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef3 String
	 */
	public void setVdef3 (String newVdef3 ) {
	 	this.vdef3 = newVdef3;
	} 	  
	/**
	 * 属性vdef6的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef6 () {
		return vdef6;
	}   
	/**
	 * 属性vdef6的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef6 String
	 */
	public void setVdef6 (String newVdef6 ) {
	 	this.vdef6 = newVdef6;
	} 	  
	/**
	 * 属性vdef5的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef5 () {
		return vdef5;
	}   
	/**
	 * 属性vdef5的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef5 String
	 */
	public void setVdef5 (String newVdef5 ) {
	 	this.vdef5 = newVdef5;
	} 	  
	/**
	 * 属性norighadsetlevefymny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNorighadsetlevefymny () {
		return norighadsetlevefymny;
	}   
	/**
	 * 属性norighadsetlevefymny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNorighadsetlevefymny UFDouble
	 */
	public void setNorighadsetlevefymny (UFDouble newNorighadsetlevefymny ) {
	 	this.norighadsetlevefymny = newNorighadsetlevefymny;
	} 	  
	/**
	 * 属性norighadsetlevefytaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNorighadsetlevefytaxmny () {
		return norighadsetlevefytaxmny;
	}   
	/**
	 * 属性norighadsetlevefytaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNorighadsetlevefytaxmny UFDouble
	 */
	public void setNorighadsetlevefytaxmny (UFDouble newNorighadsetlevefytaxmny ) {
	 	this.norighadsetlevefytaxmny = newNorighadsetlevefytaxmny;
	} 	  
	/**
	 * 属性ninvmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNinvmny () {
		return ninvmny;
	}   
	/**
	 * 属性ninvmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNinvmny UFDouble
	 */
	public void setNinvmny (UFDouble newNinvmny ) {
	 	this.ninvmny = newNinvmny;
	} 	  
	/**
	 * 属性pk_authenpsn的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_authenpsn () {
		return pk_authenpsn;
	}   
	/**
	 * 属性pk_authenpsn的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_authenpsn String
	 */
	public void setPk_authenpsn (String newPk_authenpsn ) {
	 	this.pk_authenpsn = newPk_authenpsn;
	} 	  
	/**
	 * 属性vtaxpayeraddress的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVtaxpayeraddress () {
		return vtaxpayeraddress;
	}   
	/**
	 * 属性vtaxpayeraddress的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVtaxpayeraddress String
	 */
	public void setVtaxpayeraddress (String newVtaxpayeraddress ) {
	 	this.vtaxpayeraddress = newVtaxpayeraddress;
	} 	  
	/**
	 * 属性dauthendate的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDate
	 */
	public UFDate getDauthendate () {
		return dauthendate;
	}   
	/**
	 * 属性dauthendate的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newDauthendate UFDate
	 */
	public void setDauthendate (UFDate newDauthendate ) {
	 	this.dauthendate = newDauthendate;
	} 	  
	/**
	 * 属性norignopayvefymny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNorignopayvefymny () {
		return norignopayvefymny;
	}   
	/**
	 * 属性norignopayvefymny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNorignopayvefymny UFDouble
	 */
	public void setNorignopayvefymny (UFDouble newNorignopayvefymny ) {
	 	this.norignopayvefymny = newNorignopayvefymny;
	} 	  
	/**
	 * 属性noriginvmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNoriginvmny () {
		return noriginvmny;
	}   
	/**
	 * 属性noriginvmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNoriginvmny UFDouble
	 */
	public void setNoriginvmny (UFDouble newNoriginvmny ) {
	 	this.noriginvmny = newNoriginvmny;
	} 	  
	/**
	 * 属性vtaxpayernumber的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVtaxpayernumber () {
		return vtaxpayernumber;
	}   
	/**
	 * 属性vtaxpayernumber的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVtaxpayernumber String
	 */
	public void setVtaxpayernumber (String newVtaxpayernumber ) {
	 	this.vtaxpayernumber = newVtaxpayernumber;
	} 	  
	/**
	 * 属性pk_basetype的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_basetype () {
		return pk_basetype;
	}   
	/**
	 * 属性pk_basetype的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_basetype String
	 */
	public void setPk_basetype (String newPk_basetype ) {
	 	this.pk_basetype = newPk_basetype;
	} 	  
	/**
	 * 属性noriginvtaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNoriginvtaxmny () {
		return noriginvtaxmny;
	}   
	/**
	 * 属性noriginvtaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNoriginvtaxmny UFDouble
	 */
	public void setNoriginvtaxmny (UFDouble newNoriginvtaxmny ) {
	 	this.noriginvtaxmny = newNoriginvtaxmny;
	} 	  
	/**
	 * 属性dopendate的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDate
	 */
	public UFDate getDopendate () {
		return dopendate;
	}   
	/**
	 * 属性dopendate的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newDopendate UFDate
	 */
	public void setDopendate (UFDate newDopendate ) {
	 	this.dopendate = newDopendate;
	} 	  
	/**
	 * 属性vbankaccount的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVbankaccount () {
		return vbankaccount;
	}   
	/**
	 * 属性vbankaccount的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVbankaccount String
	 */
	public void setVbankaccount (String newVbankaccount ) {
	 	this.vbankaccount = newVbankaccount;
	} 	  
	/**
	 * 属性vreserve1的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve1 () {
		return vreserve1;
	}   
	/**
	 * 属性vreserve1的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve1 String
	 */
	public void setVreserve1 (String newVreserve1 ) {
	 	this.vreserve1 = newVreserve1;
	} 	  
	/**
	 * 属性pk_psndoc的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_psndoc () {
		return pk_psndoc;
	}   
	/**
	 * 属性pk_psndoc的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_psndoc String
	 */
	public void setPk_psndoc (String newPk_psndoc ) {
	 	this.pk_psndoc = newPk_psndoc;
	} 	  
	/**
	 * 属性vtaxpayername的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVtaxpayername () {
		return vtaxpayername;
	}   
	/**
	 * 属性vtaxpayername的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVtaxpayername String
	 */
	public void setVtaxpayername (String newVtaxpayername ) {
	 	this.vtaxpayername = newVtaxpayername;
	} 	  
	/**
	 * 属性vreserve4的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve4 () {
		return vreserve4;
	}   
	/**
	 * 属性vreserve4的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve4 String
	 */
	public void setVreserve4 (String newVreserve4 ) {
	 	this.vreserve4 = newVreserve4;
	} 	  
	/**
	 * 属性vreserve5的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve5 () {
		return vreserve5;
	}   
	/**
	 * 属性vreserve5的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve5 String
	 */
	public void setVreserve5 (String newVreserve5 ) {
	 	this.vreserve5 = newVreserve5;
	} 	  
	/**
	 * 属性vreserve2的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve2 () {
		return vreserve2;
	}   
	/**
	 * 属性vreserve2的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve2 String
	 */
	public void setVreserve2 (String newVreserve2 ) {
	 	this.vreserve2 = newVreserve2;
	} 	  
	/**
	 * 属性vreserve3的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve3 () {
		return vreserve3;
	}   
	/**
	 * 属性vreserve3的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve3 String
	 */
	public void setVreserve3 (String newVreserve3 ) {
	 	this.vreserve3 = newVreserve3;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性vapprovenote的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVapprovenote () {
		return vapprovenote;
	}   
	/**
	 * 属性vapprovenote的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVapprovenote String
	 */
	public void setVapprovenote (String newVapprovenote ) {
	 	this.vapprovenote = newVapprovenote;
	} 	  
	/**
	 * 属性vsupplierphone的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVsupplierphone () {
		return vsupplierphone;
	}   
	/**
	 * 属性vsupplierphone的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVsupplierphone String
	 */
	public void setVsupplierphone (String newVsupplierphone ) {
	 	this.vsupplierphone = newVsupplierphone;
	} 	  
	/**
	 * 属性norighadpayvefytaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNorighadpayvefytaxmny () {
		return norighadpayvefytaxmny;
	}   
	/**
	 * 属性norighadpayvefytaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNorighadpayvefytaxmny UFDouble
	 */
	public void setNorighadpayvefytaxmny (UFDouble newNorighadpayvefytaxmny ) {
	 	this.norighadpayvefytaxmny = newNorighadpayvefytaxmny;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性vreserve9的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve9 () {
		return vreserve9;
	}   
	/**
	 * 属性vreserve9的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve9 String
	 */
	public void setVreserve9 (String newVreserve9 ) {
	 	this.vreserve9 = newVreserve9;
	} 	  
	/**
	 * 属性bisred的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFBoolean
	 */
	public UFBoolean getBisred () {
		return bisred;
	}   
	/**
	 * 属性bisred的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newBisred UFBoolean
	 */
	public void setBisred (UFBoolean newBisred ) {
	 	this.bisred = newBisred;
	} 	  
	/**
	 * 属性vreserve8的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve8 () {
		return vreserve8;
	}   
	/**
	 * 属性vreserve8的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve8 String
	 */
	public void setVreserve8 (String newVreserve8 ) {
	 	this.vreserve8 = newVreserve8;
	} 	  
	/**
	 * 属性vreserve7的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve7 () {
		return vreserve7;
	}   
	/**
	 * 属性vreserve7的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve7 String
	 */
	public void setVreserve7 (String newVreserve7 ) {
	 	this.vreserve7 = newVreserve7;
	} 	  
	/**
	 * 属性vreserve6的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve6 () {
		return vreserve6;
	}   
	/**
	 * 属性vreserve6的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve6 String
	 */
	public void setVreserve6 (String newVreserve6 ) {
	 	this.vreserve6 = newVreserve6;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性vtaxctrlmachno的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVtaxctrlmachno () {
		return vtaxctrlmachno;
	}   
	/**
	 * 属性vtaxctrlmachno的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVtaxctrlmachno String
	 */
	public void setVtaxctrlmachno (String newVtaxctrlmachno ) {
	 	this.vtaxctrlmachno = newVtaxctrlmachno;
	} 	  
	/**
	 * 属性vraddress的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVraddress () {
		return vraddress;
	}   
	/**
	 * 属性vraddress的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVraddress String
	 */
	public void setVraddress (String newVraddress ) {
	 	this.vraddress = newVraddress;
	} 	  
	/**
	 * 属性pk_supplier的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_supplier () {
		return pk_supplier;
	}   
	/**
	 * 属性pk_supplier的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_supplier String
	 */
	public void setPk_supplier (String newPk_supplier ) {
	 	this.pk_supplier = newPk_supplier;
	} 	  
	/**
	 * 属性pk_finance的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_finance () {
		return pk_finance;
	}   
	/**
	 * 属性pk_finance的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_finance String
	 */
	public void setPk_finance (String newPk_finance ) {
	 	this.pk_finance = newPk_finance;
	} 	  
	/**
	 * 属性pk_project的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_project () {
		return pk_project;
	}   
	/**
	 * 属性pk_project的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_project String
	 */
	public void setPk_project (String newPk_project ) {
	 	this.pk_project = newPk_project;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
	 	this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性pk_deptdoc的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_deptdoc () {
		return pk_deptdoc;
	}   
	/**
	 * 属性pk_deptdoc的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_deptdoc String
	 */
	public void setPk_deptdoc (String newPk_deptdoc ) {
	 	this.pk_deptdoc = newPk_deptdoc;
	} 	  
	/**
	 * 属性pk_supplierbase的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_supplierbase () {
		return pk_supplierbase;
	}   
	/**
	 * 属性pk_supplierbase的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_supplierbase String
	 */
	public void setPk_supplierbase (String newPk_supplierbase ) {
	 	this.pk_supplierbase = newPk_supplierbase;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vinvcode的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVinvcode () {
		return vinvcode;
	}   
	/**
	 * 属性vinvcode的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVinvcode String
	 */
	public void setVinvcode (String newVinvcode ) {
	 	this.vinvcode = newVinvcode;
	} 	  
	/**
	 * 属性dmakedate的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDate
	 */
	public UFDate getDmakedate () {
		return dmakedate;
	}   
	/**
	 * 属性dmakedate的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newDmakedate UFDate
	 */
	public void setDmakedate (UFDate newDmakedate ) {
	 	this.dmakedate = newDmakedate;
	} 	  
	/**
	 * 属性vtaxpayerphone的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVtaxpayerphone () {
		return vtaxpayerphone;
	}   
	/**
	 * 属性vtaxpayerphone的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVtaxpayerphone String
	 */
	public void setVtaxpayerphone (String newVtaxpayerphone ) {
	 	this.vtaxpayerphone = newVtaxpayerphone;
	} 	  
	/**
	 * 属性vsupbankaccount的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVsupbankaccount () {
		return vsupbankaccount;
	}   
	/**
	 * 属性vsupbankaccount的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVsupbankaccount String
	 */
	public void setVsupbankaccount (String newVsupbankaccount ) {
	 	this.vsupbankaccount = newVsupbankaccount;
	} 	  
	/**
	 * 属性norignosetlevefytaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNorignosetlevefytaxmny () {
		return norignosetlevefytaxmny;
	}   
	/**
	 * 属性norignosetlevefytaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNorignosetlevefytaxmny UFDouble
	 */
	public void setNorignosetlevefytaxmny (UFDouble newNorignosetlevefytaxmny ) {
	 	this.norignosetlevefytaxmny = newNorignosetlevefytaxmny;
	} 	  
	/**
	 * 属性vtaxsuppliernumber的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVtaxsuppliernumber () {
		return vtaxsuppliernumber;
	}   
	/**
	 * 属性vtaxsuppliernumber的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVtaxsuppliernumber String
	 */
	public void setVtaxsuppliernumber (String newVtaxsuppliernumber ) {
	 	this.vtaxsuppliernumber = newVtaxsuppliernumber;
	} 	  
	/**
	 * 属性pk_receive_ref的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_receive_ref () {
		return pk_receive_ref;
	}   
	/**
	 * 属性pk_receive_ref的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_receive_ref String
	 */
	public void setPk_receive_ref (String newPk_receive_ref ) {
	 	this.pk_receive_ref = newPk_receive_ref;
	} 	  
	/**
	 * 属性nbaserate的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNbaserate () {
		return nbaserate;
	}   
	/**
	 * 属性nbaserate的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNbaserate UFDouble
	 */
	public void setNbaserate (UFDouble newNbaserate ) {
	 	this.nbaserate = newNbaserate;
	} 	  
	/**
	 * 属性nhadsetlevefymny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNhadsetlevefymny () {
		return nhadsetlevefymny;
	}   
	/**
	 * 属性nhadsetlevefymny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNhadsetlevefymny UFDouble
	 */
	public void setNhadsetlevefymny (UFDouble newNhadsetlevefymny ) {
	 	this.nhadsetlevefymny = newNhadsetlevefymny;
	} 	  
	/**
	 * 属性vreserve10的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVreserve10 () {
		return vreserve10;
	}   
	/**
	 * 属性vreserve10的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVreserve10 String
	 */
	public void setVreserve10 (String newVreserve10 ) {
	 	this.vreserve10 = newVreserve10;
	} 	  
	/**
	 * 属性pk_billtype的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_billtype () {
		return pk_billtype;
	}   
	/**
	 * 属性pk_billtype的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_billtype String
	 */
	public void setPk_billtype (String newPk_billtype ) {
	 	this.pk_billtype = newPk_billtype;
	} 	  
	/**
	 * 属性ntaxrate的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNtaxrate () {
		return ntaxrate;
	}   
	/**
	 * 属性ntaxrate的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNtaxrate UFDouble
	 */
	public void setNtaxrate (UFDouble newNtaxrate ) {
	 	this.ntaxrate = newNtaxrate;
	} 	  
	/**
	 * 属性vdef10的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef10 () {
		return vdef10;
	}   
	/**
	 * 属性vdef10的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef10 String
	 */
	public void setVdef10 (String newVdef10 ) {
	 	this.vdef10 = newVdef10;
	} 	  
	/**
	 * 属性vdef11的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef11 () {
		return vdef11;
	}   
	/**
	 * 属性vdef11的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef11 String
	 */
	public void setVdef11 (String newVdef11 ) {
	 	this.vdef11 = newVdef11;
	} 	  
	/**
	 * 属性bisauthen的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFBoolean
	 */
	public UFBoolean getBisauthen () {
		return bisauthen;
	}   
	/**
	 * 属性bisauthen的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newBisauthen UFBoolean
	 */
	public void setBisauthen (UFBoolean newBisauthen ) {
	 	this.bisauthen = newBisauthen;
	} 	  
	/**
	 * 属性vdef15的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef15 () {
		return vdef15;
	}   
	/**
	 * 属性vdef15的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef15 String
	 */
	public void setVdef15 (String newVdef15 ) {
	 	this.vdef15 = newVdef15;
	} 	  
	/**
	 * 属性vinvno的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVinvno () {
		return vinvno;
	}   
	/**
	 * 属性vinvno的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVinvno String
	 */
	public void setVinvno (String newVinvno ) {
	 	this.vinvno = newVinvno;
	} 	  
	/**
	 * 属性vdef14的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef14 () {
		return vdef14;
	}   
	/**
	 * 属性vdef14的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef14 String
	 */
	public void setVdef14 (String newVdef14 ) {
	 	this.vdef14 = newVdef14;
	} 	  
	/**
	 * 属性vdef13的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef13 () {
		return vdef13;
	}   
	/**
	 * 属性vdef13的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef13 String
	 */
	public void setVdef13 (String newVdef13 ) {
	 	this.vdef13 = newVdef13;
	} 	  
	/**
	 * 属性vdef12的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef12 () {
		return vdef12;
	}   
	/**
	 * 属性vdef12的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef12 String
	 */
	public void setVdef12 (String newVdef12 ) {
	 	this.vdef12 = newVdef12;
	} 	  
	/**
	 * 属性vdef19的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef19 () {
		return vdef19;
	}   
	/**
	 * 属性vdef19的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef19 String
	 */
	public void setVdef19 (String newVdef19 ) {
	 	this.vdef19 = newVdef19;
	} 	  
	/**
	 * 属性vdef18的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef18 () {
		return vdef18;
	}   
	/**
	 * 属性vdef18的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef18 String
	 */
	public void setVdef18 (String newVdef18 ) {
	 	this.vdef18 = newVdef18;
	} 	  
	/**
	 * 属性pk_industryclassify的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_industryclassify () {
		return pk_industryclassify;
	}   
	/**
	 * 属性pk_industryclassify的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_industryclassify String
	 */
	public void setPk_industryclassify (String newPk_industryclassify ) {
	 	this.pk_industryclassify = newPk_industryclassify;
	} 	  
	/**
	 * 属性vdef17的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef17 () {
		return vdef17;
	}   
	/**
	 * 属性vdef17的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef17 String
	 */
	public void setVdef17 (String newVdef17 ) {
	 	this.vdef17 = newVdef17;
	} 	  
	/**
	 * 属性vdef16的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef16 () {
		return vdef16;
	}   
	/**
	 * 属性vdef16的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef16 String
	 */
	public void setVdef16 (String newVdef16 ) {
	 	this.vdef16 = newVdef16;
	} 	  
	/**
	 * 属性dbilldate的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDate
	 */
	public UFDate getDbilldate () {
		return dbilldate;
	}   
	/**
	 * 属性dbilldate的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newDbilldate UFDate
	 */
	public void setDbilldate (UFDate newDbilldate ) {
	 	this.dbilldate = newDbilldate;
	} 	  
	/**
	 * 属性ninvtaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNinvtaxmny () {
		return ninvtaxmny;
	}   
	/**
	 * 属性ninvtaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNinvtaxmny UFDouble
	 */
	public void setNinvtaxmny (UFDouble newNinvtaxmny ) {
	 	this.ninvtaxmny = newNinvtaxmny;
	} 	  
	/**
	 * 属性pk_bank的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_bank () {
		return pk_bank;
	}   
	/**
	 * 属性pk_bank的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_bank String
	 */
	public void setPk_bank (String newPk_bank ) {
	 	this.pk_bank = newPk_bank;
	} 	  
	/**
	 * 属性norighadpayvefymny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNorighadpayvefymny () {
		return norighadpayvefymny;
	}   
	/**
	 * 属性norighadpayvefymny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNorighadpayvefymny UFDouble
	 */
	public void setNorighadpayvefymny (UFDouble newNorighadpayvefymny ) {
	 	this.norighadpayvefymny = newNorighadpayvefymny;
	} 	  
	/**
	 * 属性pk_origintype的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_origintype () {
		return pk_origintype;
	}   
	/**
	 * 属性pk_origintype的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_origintype String
	 */
	public void setPk_origintype (String newPk_origintype ) {
	 	this.pk_origintype = newPk_origintype;
	} 	  
	/**
	 * 属性norignopayvefytaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNorignopayvefytaxmny () {
		return norignopayvefytaxmny;
	}   
	/**
	 * 属性norignopayvefytaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNorignopayvefytaxmny UFDouble
	 */
	public void setNorignopayvefytaxmny (UFDouble newNorignopayvefytaxmny ) {
	 	this.norignopayvefytaxmny = newNorignopayvefytaxmny;
	} 	  
	/**
	 * 属性vdef20的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVdef20 () {
		return vdef20;
	}   
	/**
	 * 属性vdef20的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVdef20 String
	 */
	public void setVdef20 (String newVdef20 ) {
	 	this.vdef20 = newVdef20;
	} 	  
	/**
	 * 属性nnopayvefymny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNnopayvefymny () {
		return nnopayvefymny;
	}   
	/**
	 * 属性nnopayvefymny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNnopayvefymny UFDouble
	 */
	public void setNnopayvefymny (UFDouble newNnopayvefymny ) {
	 	this.nnopayvefymny = newNnopayvefymny;
	} 	  
	/**
	 * 属性vsupplieraddress的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVsupplieraddress () {
		return vsupplieraddress;
	}   
	/**
	 * 属性vsupplieraddress的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVsupplieraddress String
	 */
	public void setVsupplieraddress (String newVsupplieraddress ) {
	 	this.vsupplieraddress = newVsupplieraddress;
	} 	  
	/**
	 * 属性vmemo的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVmemo () {
		return vmemo;
	}   
	/**
	 * 属性vmemo的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVmemo String
	 */
	public void setVmemo (String newVmemo ) {
	 	this.vmemo = newVmemo;
	} 	  
	/**
	 * 属性nhadpayvefymny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNhadpayvefymny () {
		return nhadpayvefymny;
	}   
	/**
	 * 属性nhadpayvefymny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNhadpayvefymny UFDouble
	 */
	public void setNhadpayvefymny (UFDouble newNhadpayvefymny ) {
	 	this.nhadpayvefymny = newNhadpayvefymny;
	} 	  
	/**
	 * 属性nhadpayvefytaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNhadpayvefytaxmny () {
		return nhadpayvefytaxmny;
	}   
	/**
	 * 属性nhadpayvefytaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNhadpayvefytaxmny UFDouble
	 */
	public void setNhadpayvefytaxmny (UFDouble newNhadpayvefytaxmny ) {
	 	this.nhadpayvefytaxmny = newNhadpayvefytaxmny;
	} 	  
	/**
	 * 属性nhadsetlevefytaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNhadsetlevefytaxmny () {
		return nhadsetlevefytaxmny;
	}   
	/**
	 * 属性nhadsetlevefytaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNhadsetlevefytaxmny UFDouble
	 */
	public void setNhadsetlevefytaxmny (UFDouble newNhadsetlevefytaxmny ) {
	 	this.nhadsetlevefytaxmny = newNhadsetlevefytaxmny;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性bisopenred的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFBoolean
	 */
	public UFBoolean getBisopenred () {
		return bisopenred;
	}   
	/**
	 * 属性bisopenred的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newBisopenred UFBoolean
	 */
	public void setBisopenred (UFBoolean newBisopenred ) {
	 	this.bisopenred = newBisopenred;
	} 	  
	/**
	 * 属性vphone的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getVphone () {
		return vphone;
	}   
	/**
	 * 属性vphone的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVphone String
	 */
	public void setVphone (String newVphone ) {
	 	this.vphone = newVphone;
	} 	  
	/**
	 * 属性nnopayvefytaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNnopayvefytaxmny () {
		return nnopayvefytaxmny;
	}   
	/**
	 * 属性nnopayvefytaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNnopayvefytaxmny UFDouble
	 */
	public void setNnopayvefytaxmny (UFDouble newNnopayvefytaxmny ) {
	 	this.nnopayvefytaxmny = newNnopayvefytaxmny;
	} 	  
	/**
	 * 属性pk_receive的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return String
	 */
	public String getPk_receive () {
		return pk_receive;
	}   
	/**
	 * 属性pk_receive的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newPk_receive String
	 */
	public void setPk_receive (String newPk_receive ) {
	 	this.pk_receive = newPk_receive;
	} 	  
	/**
	 * 属性norignosetlevefymny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNorignosetlevefymny () {
		return norignosetlevefymny;
	}   
	/**
	 * 属性norignosetlevefymny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNorignosetlevefymny UFDouble
	 */
	public void setNorignosetlevefymny (UFDouble newNorignosetlevefymny ) {
	 	this.norignosetlevefymny = newNorignosetlevefymny;
	} 	  
	/**
	 * 属性nnosetlevefymny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNnosetlevefymny () {
		return nnosetlevefymny;
	}   
	/**
	 * 属性nnosetlevefymny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNnosetlevefymny UFDouble
	 */
	public void setNnosetlevefymny (UFDouble newNnosetlevefymny ) {
	 	this.nnosetlevefymny = newNnosetlevefymny;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return Integer
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newVbillstatus Integer
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDate
	 */
	public UFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate (UFDate newDapprovedate ) {
	 	this.dapprovedate = newDapprovedate;
	} 	  
	/**
	 * 属性nnosetlevefytaxmny的Getter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @return UFDouble
	 */
	public UFDouble getNnosetlevefytaxmny () {
		return nnosetlevefytaxmny;
	}   
	/**
	 * 属性nnosetlevefytaxmny的Setter方法.
	 * 创建日期:2016-03-16 10:46:06
	 * @param newNnosetlevefytaxmny UFDouble
	 */
	public void setNnosetlevefytaxmny (UFDouble newNnosetlevefytaxmny ) {
	 	this.nnosetlevefytaxmny = newNnosetlevefytaxmny;
	} 	  
	/**
	 * 属性pk_paycorp的Getter方法.
	 * 创建日期:2016-03-16 16:14:50
	 * @return String
	 */
	public String getPk_paycorp () {
		return pk_paycorp;
	}   
	/**
	 * 属性pk_paycorp的Setter方法.
	 * 创建日期:2016-03-16 16:14:50
	 * @param newPk_paycorp String
	 */
	public void setPk_paycorp (String newPk_paycorp ) {
	 	this.pk_paycorp = newPk_paycorp;
	} 
	/**
	 * 属性pk_contract的Getter方法.
	 * 创建日期:2016-03-12 20:26:54
	 * @return String
	 */
	public String getPk_contract () {
		return pk_contract;
	}   
	/**
	 * 属性pk_contract的Setter方法.
	 * 创建日期:2016-03-12 20:26:54
	 * @param newPk_contract String
	 */
	public void setPk_contract (String newPk_contract ) {
	 	this.pk_contract = newPk_contract;
	} 
	
	public UFBoolean getBisdrawback() {
		return bisdrawback;
	}
	public void setBisdrawback(UFBoolean bisdrawback) {
		this.bisdrawback = bisdrawback;
	}
	
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2016-03-16 10:46:06
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
	//费用已抵扣金额(无税)
	public UFDouble getNoriginfhaddductmny() {
		return noriginfhaddductmny;
	}
	public void setNoriginfhaddductmny(UFDouble noriginfhaddductmny) {
		this.noriginfhaddductmny = noriginfhaddductmny;
	}
	public UFDouble getNoriginfhaddducttaxmny() {
		return noriginfhaddducttaxmny;
	}
	public void setNoriginfhaddducttaxmny(UFDouble noriginfhaddducttaxmny) {
		this.noriginfhaddducttaxmny = noriginfhaddducttaxmny;
	}
	public UFDouble getNfhaddductmny() {
		return nfhaddductmny;
	}
	public void setNfhaddductmny(UFDouble nfhaddductmny) {
		this.nfhaddductmny = nfhaddductmny;
	}
	public UFDouble getNfhaddducttaxmny() {
		return nfhaddducttaxmny;
	}
	public void setNfhaddducttaxmny(UFDouble nfhaddducttaxmny) {
		this.nfhaddducttaxmny = nfhaddducttaxmny;
	}
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2016-03-16 10:46:06
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_receive";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2016-03-16 10:46:06
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "jzinv_receive";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2016-03-16 10:46:06
	  */
     public ReceiveVO() {
		super();	
	}
	public String[] getBillCodeArray() {
		// TODO Auto-generated method stub
		return null;
	}    
} 
	